[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
# startup_mode = "Maximized"
# decorations = "none"

[window.dimensions]
lines = 20
columns = 80

